### ISSUE TITLE
TypeError: argument of type 'PosixPath' is not iterable

### ISSUE THREAD

**Issue by JachinMa** [zhutmost/lsq-net#3]
I tried to run 'python main.py config.yaml',but faced this problem:

Traceback (most recent call last):
  File "main.py", line 103, in <module>
    main()
  File "main.py", line 18, in main
    log_dir = util.init_logger(args.name, output_dir, 'logging.conf')
  File "/home/j/Downloads/lsq-net-master/util/config.py", line 46, in init_logger
    logging.config.fileConfig(cfg_file, defaults={'logfilename': log_file})
  File "/home/j/anaconda3/envs/py14/lib/python3.6/logging/config.py", line 84, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/home/j/anaconda3/envs/py14/lib/python3.6/logging/config.py", line 146, in _install_handlers
    args = section["args"]
  File "/home/j/anaconda3/envs/py14/lib/python3.6/configparser.py", line 1234, in __getitem__
    return self._parser.get(self._name, key)
  File "/home/j/anaconda3/envs/py14/lib/python3.6/configparser.py", line 800, in get
    d)
  File "/home/j/anaconda3/envs/py14/lib/python3.6/configparser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/home/j/anaconda3/envs/py14/lib/python3.6/configparser.py", line 435, in _interpolate_some
    if "%" in v:
TypeError: argument of type 'PosixPath' is not iterable

I tried py1.4 and py1.5,they all dont work.

can you tell me how to deal with it?

**Comment by zhutmost** [comment]
It seems to be a Python-scope problem. 

I don't know what py1.4 & 1.5 refer to. I work on the latest version of Anaconda3.

**Comment by zhutmost** [comment]
If you have solve your problem, pls let me know.

**Comment by zhutmost** [comment]
I have tried my code on python 3.6, and the same error occurs. 
Please update your python to 3.8, and have a try again. And the pytorch version must be 1.4. It is incompatible with the latest version i.e. v1.5. I will bump to the new version soon :D

**Comment by dailingjun** [comment]
Do not use python3.6 or replace the Line46 in util/config.py with "logging.config.fileConfig(cfg_file, defaults={'logfilename': log_file.__str__()})".
